# Uncomment this if your project is hosted on GitHub:
# github_url = "https://github.com/<user or organization>/<project>/"
[version]
current = "1.2.0+d3c6"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  (\-(?P<pre>[a-z\.\d]+))?
  (\+(?P<build>.+))?
  '''

[git]
message_template = '"Bump to {new_version}"'
tag_template = "v{new_version}"

[[before_commit]]
name = "Build"
cmd = '''run clean; run all;
         cp -rT docs/_build deliverables;         # copy main deliverable overwritting the destination
         cp notebooks/_build/*.html deliverables; # copy supporting deliverables
         tree ./deliverables -H '.' -T "Template Paper" > deliverables/index.html
         '''

# For each file to patch, add a [[file]] config
# section containing the path of the file, relative to the
# tbump.toml location.
# Replace version in YAML front matter
[[file]]
src =   'docs/paper.qmd'
search ='^[\w-]*: .*{current_version}' 
